spring:
  datasource:
    url: jdbc:postgresql://postgres-rec:5432/recommendation_service
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080/realms/persea
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      url: redis://redis:6379

kafka:
  topics:
    products-cdc:           data.cdc.public.products
    product-categories-cdc: data.cdc.public.categories
    product-brands-cdc:     data.cdc.public.brands
    user-actions-cdc:       data.cdc.public.user_actions
    user-action-types-cdc:  data.cdc.public.user_action_types
  consumer-groups:
    products-sync:           recommendation-service-products.cdc.sync
    product-categories-sync: recommendation-service-product-categories.cdc.sync
    product-brands-sync:     recommendation-service-product-brands.cdc.sync
    user-actions-sync:       recommendation-service-user-actions.cdc.sync
    user-action-types-sync:  recommendation-service-user-action-types.cdc.sync
